--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: pbcouk
    type: hugo
  name: pbcouk-hugo-v0
spec: 
  replicas: 2
  selector: 
    service: pbcouk
    type: hugo
    version: v0
  template: 
    metadata: 
      labels: 
        service: pbcouk
        type: hugo
        version: v0
    spec:
      containers: 
        - 
          image: quay.io/purplebooth/purplebooth-co-uk-v2
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          name: pbcouk-hugo
          ports: 
            - 
              containerPort: 80
              name: http
              protocol: TCP
      restartPolicy: Always
