--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: pbcouk
    type: hugo
  name: pbcouk-hugo
spec:
  replicas: 2
  selector:
    name: pbcouk-hugo
  template:
    metadata:
      labels:
        name: pbcouk-hugo
    spec:
      containers:
        -
          image: quay.io/purplebooth/purplebooth-co-uk-v2
          imagePullPolicy: Always
          name: pbcouk-hugo
          ports:
            -
              containerPort: 80
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 1
      restartPolicy: Always
