--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    facing: front
    service: pbcouk
    type: nginx
  name: pbcouk-nginx
spec: 
  ports: 
    - 
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    - 
      name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector: 
    service: pbcouk
    type: nginx
  type: LoadBalancer
