--- 
apiVersion: v1
kind: ReplicationController
metadata: 
  labels: 
    facing: front
    service: pbcouk
    type: nginx
  name: pbcouk-nginx-v0
spec: 
  replicas: 2
  selector: 
    service: pbcouk
    type: nginx
    version: v0
  template: 
    metadata: 
      labels: 
        service: pbcouk
        type: nginx
        version: v0
    spec: 
      containers: 
        - 
          env: 
            - 
              name: SSL_CRT_PATH
              value: /certs/purplebooth-co-uk.crt
            - 
              name: SSL_KEY_PATH
              value: /certs/purplebooth-co-uk.key
            - 
              name: UPSTREAM
              value: "pbcouk-hugo:80"
          image: quay.io/purplebooth/nginx-ssl-terminator
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
          name: pbcouk-nginx
          ports: 
            - 
              containerPort: 80
              name: http
              protocol: TCP
            - 
              containerPort: 443
              name: https
              protocol: TCP
          volumeMounts: 
            - 
              mountPath: /certs
              name: ssl-certs
      restartPolicy: Always
      volumes: 
        - 
          name: ssl-certs
          secret: 
            secretName: ssl-certs
