queue_rules:
  - name: default
    speculative_checks: 20
    batch_size: 20
    conditions:
      - check-success=Install dependencies
      - check-success=Create production build
      - check-success=Lint code
      - check-success=Check coding style
      - check-success=Run unit tests
      - check-success=Run end to end tests
      - check-success=Analyze (javascript)

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - base=main
      - label=dependencies
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Install dependencies
      - check-success=Create production build
      - check-success=Lint code
      - check-success=Check coding style
      - check-success=Run unit tests
      - check-success=Run end to end tests
      - check-success=Analyze (javascript)
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default

