baseurl = "https://purplebooth.co.uk"
languageCode = "en-gb"
title = "Purple Booth"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "Billie Thompson"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    logo = "Purple Booth Logo-01.png"
    Description = "Billie Thompson. Software developer."
    GoogleAnalytics = "UA-32113064-1"
    # Used when a given page doesn't set its own.
    defaultDescription = "Adventures in coding"
    defaultKeywords = "Coding,Billie Thompson,blog"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-06"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "idea"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Billie Thompson. Software developer."

    # Metadata used to drive integrations.
    googleAuthorship = "+PurpleboothCoUk"
    googleAnalytics = "UA-32113064-1"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/PurpleBooth"
    linkedin = "https://uk.linkedin.com/in/purplebooth"
    twitter = "https://twitter.com/PurpleBooth"
    googleplus = "https://www.google.com/+PurpleboothCoUk"
