[build]
publish = ".next"

command = "yarn run build && yarn run postbuild"

[functions]
directory = "netlify/functions"
included_files = ["content/**/*"]

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
NODE_ENV = "production"
