[build]
publish = ".next"

command = "yarn dlx prettier -c services/ components/ pages/ styles/ && NODE_ENV=\"test\" yarn run test && yarn run lint && yarn run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
 package = "@netlify/plugin-lighthouse"
 # to audit a specific absolute url
 [[plugins.inputs.audits]]
 url = "http://localhost:3000"

[context.production.environment]
NODE_ENV = "production"
