[build]
publish = ".next"

command = "yarn dlx prettier -c services/ components/ pages/ styles/ && yarn run test && yarn run lint && yarn run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
NODE_ENV = "production"
