apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: gcr.io/purplebooth-gke/github-purplebooth-purplebooth-co-uk-v2
deploy:
  helm:
    releases:
    - name: lovely-ant
      chartPath: helm
      namespace: default
      values:
        image: gcr.io/purplebooth-gke/github-purplebooth-purplebooth-co-uk-v2
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: purplebooth-gke
