apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: {{ .Values.replicaCount.min }}
  maxReplicas: {{ .Values.replicaCount.max }}
  targetCPUUtilizationPercentage:  {{ .Values.replicaCount.targetCPUUtilizationPercentage }}
