apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - secretName: {{ template "fullname" . }}-tls
    hosts:
    - {{ .Values.fqdn.canonical }}
    - {{ .Values.fqdn.www }}
  rules:
  - host: {{ .Values.fqdn.canonical }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.portName }}
  - host: {{ .Values.fqdn.www }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.portName }}
